In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a.ndim

1

In [5]:
a.dtype
a.itemsize
a.nbytes

12

In [6]:
array = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
array[1,5]

12

In [8]:
array[0,4]

5

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones((3,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [15]:
np.random.rand(5,2)

array([[0.54787818, 0.24441816],
       [0.65736434, 0.19695757],
       [0.3227662 , 0.64905069],
       [0.17311015, 0.65812855],
       [0.12629713, 0.87209197]])

In [16]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
step_one = np.ones((5,5))
print(step_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
step_two = np.zeros((3,3))
step_two[1,1] = 9
print(step_two)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [23]:
step_one[1:4,1:4] = step_two
print(step_one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
copy_matrix = step_one.copy()
print(copy_matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
np.vstack([step_one, copy_matrix])

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.hstack([step_one, copy_matrix])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1., 1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])