# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
null_1 = np.zeros(10)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
null_1[4] = 1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
b = np.flip(a)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
square_3 = np.arange(9).reshape(3,3)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
c = np.array([1,2,0,0,4,0])
np.nonzero(c)

(array([0, 1, 4], dtype=int64),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
tensor_3 = np.random.rand(3,3,3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
matrix_10 = np.random.rand(10,10)
print(np.max(matrix_10))
print(np.min(matrix_10))

0.9905353407980287
0.013495807478732358


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
vector_30 = np.random.rand(30)
np.mean(vector_30)

0.5461026942497722

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
d = np.zeros((5,5))
e = np.ones((7,7))
e[1:6,1:6] = d
print(e)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

If the existing array is n by m, create a new array of size n+1 by m+1 with the `np.zeros` function, and then replace all the values inside the border (`[1:n+1, 1:m+1]`) with the existing array

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
f = np.zeros((5,5))
f[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [50]:
g = np.arange(6*7*8).reshape(6,7,8)
np.where(g == 99)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
random_5 = np.random.rand(5,5)
rand_max, rand_min = random_5.max(), random_5.min()
random_5 = (random_5 - rand_min) / (rand_max - rand_min)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [66]:
h = np.arange(11)
neg = (h > 3) & (h < 8)
h[neg] *= -1
print(h)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 29. How to round away from zero a float array ? (★☆☆)

Define a `for` loop and if the array values are greater than zero, use `np.ceil()`; otherwise, use `np.floor()`

#### 30. How to find common values between two arrays? (★☆☆)

Use `np.intersect1d(array1, array2)`

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [67]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [68]:
rng = np.random.default_rng(12345)
int_10 = rng.integers(1, 100, 10)
int_10

array([70, 23, 79, 32, 21, 79, 64, 67, 98, 39], dtype=int64)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [78]:
i = np.linspace(0,1,12, endpoint = True)[1:-1]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [80]:
j = np.random.rand(10)
j.sort()

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [83]:
rand1 = np.random.rand(1,5,8)
rand2 = np.random.rand(1,5,8)
eq = np.allclose(rand1, rand2)
print(eq)

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [88]:
k = np.random.rand(10)
k[k.argmax()] = 0

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

With a vector `v` and a scalar `s`, transform the elements of `v` by taking the absolute value of the difference between element in `v` and `s`, and use `argmin()` to return a position for the index in `v`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

From the original float array `x` with `dtype = np.int32`, use `x.astype(np.float32, copy = False`)

#### 59. How to sort an array by the nth column? (★★☆)

With an array `x`, use `np.sort(x, axis = n)`

#### 60. How to tell if a given 2D array has null columns? (★★☆)

With an array `x`, use `x.any(axis = 0).any()`

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [92]:
l = np.array([1,2,3,4,5])
m = np.zeros(len(l) + 3 * ((len(l) - 1)))
m[::4] = l

#### 72. How to swap two rows of an array? (★★★)

Use the method `x[[n,m]] = x[[m,n]]`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

To negate boolean, use `np.logical_not(x, out = x)`; to change float sign, use `np.negative(x, out = x)`

#### 83. How to find the most frequent value in an array?

Use `np.bincount(x).argmax()`

#### 89. How to get the n largest values of an array (★★★)

Use `np.argsort(x)[-n:]`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

Use `np.unique(x, axis = 0)`